#!/usr/bin/env node
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';
import fg from 'fast-glob';
import { minify } from 'terser';
import { createPatch } from 'diff';
import { transform as lightningTransform } from 'lightningcss';
import { compile as refCompile, compileModule as refCompileModule } from 'svelte/compiler';
import { compile as ourCompile, compileModule as ourCompileModule } from '@mrwaip/svelte-rs2/compiler';
import { transformSync as oxcTransformSync } from 'oxc-transform';
import { parse as acornParse } from 'acorn';

function stripTsToJs(source) {
  return oxcTransformSync('input.ts', source).code;
}


const VERSION_BANNER = /^\/\*.*?generated by Svelte.*?\*\/\n/;

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const dev = args.includes('--dev');
const ssr = args.includes('--ssr');
const printDiffs = args.includes('--print-diffs');
const positional = args.filter((a) => !a.startsWith('--'));
const arg = positional[0];
if (!arg) {
  console.error('usage: svelte-rs2-sweep [--dry-run] [--dev] [--ssr] [--print-diffs] <directory>');
  process.exit(2);
}

const root = resolve(arg);
if (!existsSync(root) || !statSync(root).isDirectory()) {
  console.error(`svelte-rs2-sweep: not a directory: ${root}`);
  process.exit(2);
}

const files = await fg(['**/*.svelte', '**/*.svelte.js', '**/*.svelte.ts'], {
  cwd: root,
  absolute: true,
  onlyFiles: true,
  followSymbolicLinks: false,
  suppressErrors: true
});

if (files.length === 0) {
  console.error(`svelte-rs2-sweep: no svelte files found in ${root}`);
  process.exit(2);
}

files.sort();

const total = files.length;
const isTTY = Boolean(process.stdout.isTTY);
console.log(`cwd: ${process.cwd()}`);
console.log(`scan: ${root}`);
console.log(`mode: ${dryRun ? 'dry-run' : 'stop-on-first'}`);
console.log(`dev: ${dev}`);
console.log(`generate: ${ssr ? 'server' : 'client'}`);
console.log(`found ${total} files`);

const buckets = {
  'rust-error': [],
  'reference-error': [],
  'errors-differ': [],
  'diagnostics-mismatch': [],
  js: [],
  css: [],
  'format-error': []
};
let ok = 0;
let processed = 0;

for (const file of files) {
  reportProgress(processed, total, ok, file);
  const isModule = file.endsWith('.svelte.js') || file.endsWith('.svelte.ts');
  const isTsModule = file.endsWith('.svelte.ts');
  const source = await readFile(file, 'utf8');
  const rootDir = process.cwd();
  const options = isModule
    ? { dev, filename: file, rootDir, ...(ssr ? { generate: 'server' } : {}) }
    : { generate: ssr ? 'server' : 'client', dev, filename: file, rootDir, discloseVersion: false, modernAst: true };

  let compileSource = source;
  if (isTsModule) {
    try {
      compileSource = stripTsToJs(source);
    } catch (err) {
      handleMismatch(file, options, 'format-error', { kind: 'ok' }, { kind: 'ok' }, null, err);
      processed += 1;
      continue;
    }
  }

  const ours = runCompile(isModule ? ourCompileModule : ourCompile, compileSource, options);
  const theirs = runCompile(isModule ? refCompileModule : refCompile, compileSource, options);

  if (ours.kind === 'error' || theirs.kind === 'error') {
    if (errorsParity(ours, theirs)) {
      ok += 1;
      processed += 1;
      continue;
    }
    handleMismatch(file, options, errorReason(ours, theirs), ours, theirs, null);
    processed += 1;
    continue;
  }

  if (theirs.diagnostics.size > 0) {
    if (setsEqual(ours.diagnostics, theirs.diagnostics)) {
      ok += 1;
      processed += 1;
      continue;
    }
    handleMismatch(file, options, 'diagnostics-mismatch', ours, theirs, null);
    processed += 1;
    continue;
  }
  if (ours.diagnostics.size > 0) {
    handleMismatch(file, options, 'diagnostics-mismatch', ours, theirs, null);
    processed += 1;
    continue;
  }

  const ourJsRaw = stripComments(stripBanner(canonicalizeInjectedCss(ours.js), isModule));
  const theirJsRaw = stripComments(stripBanner(canonicalizeInjectedCss(theirs.js), isModule));
  const jsFormatted = await tryFormatBoth(formatJs, ourJsRaw, theirJsRaw);
  if (jsFormatted.kind === 'both-failed') {
    if (normalizeWs(ourJsRaw) === normalizeWs(theirJsRaw)) {
      ok += 1;
      processed += 1;
      continue;
    }
    handleMismatch(file, options, 'format-error', ours, theirs, null, jsFormatted.err, 0, jsFormatted.side);
    processed += 1;
    continue;
  }
  if (jsFormatted.kind === 'one-failed') {
    handleMismatch(file, options, 'format-error', ours, theirs, null, jsFormatted.err, 0, jsFormatted.side);
    processed += 1;
    continue;
  }
  if (jsFormatted.ours !== jsFormatted.theirs) {
    handleMismatch(file, options, 'js', ours, theirs, { ours: jsFormatted.ours, theirs: jsFormatted.theirs }, null, diffSize(jsFormatted.theirs, jsFormatted.ours));
    processed += 1;
    continue;
  }

  const cssFormatted = await tryFormatBoth(formatCss, ours.css ?? '', theirs.css ?? '');
  if (cssFormatted.kind === 'both-failed') {
    if (normalizeWs(ours.css ?? '') === normalizeWs(theirs.css ?? '')) {
      ok += 1;
      processed += 1;
      continue;
    }
    handleMismatch(file, options, 'format-error', ours, theirs, null, cssFormatted.err, 0, cssFormatted.side);
    processed += 1;
    continue;
  }
  if (cssFormatted.kind === 'one-failed') {
    handleMismatch(file, options, 'format-error', ours, theirs, null, cssFormatted.err, 0, cssFormatted.side);
    processed += 1;
    continue;
  }
  if (cssFormatted.ours !== cssFormatted.theirs) {
    handleMismatch(file, options, 'css', ours, theirs, { ours: cssFormatted.ours, theirs: cssFormatted.theirs }, null, diffSize(cssFormatted.theirs, cssFormatted.ours));
    processed += 1;
    continue;
  }

  ok += 1;
  processed += 1;
}

clearProgress();

if (dryRun) {
  const totalBad = total - ok;
  for (const [reason, list] of Object.entries(buckets)) {
    if (list.length === 0) continue;
    console.log();
    if (reason === 'js' || reason === 'css') {
      const sized = list.slice().sort((a, b) => b.size - a.size);
      const subs = { xs: [], s: [], m: [], l: [], xl: [] };
      for (const item of sized) subs[sizeBucket(item.size)].push(item);
      console.log(`[${reason}] ${list.length}`);
      for (const [tag, items] of Object.entries(subs)) {
        if (items.length === 0) continue;
        console.log(`  [${tag}] ${items.length}`);
        for (const { file: path, size } of items) console.log(`    ${path} (${size})`);
      }
    } else {
      console.log(`[${reason}] ${list.length}`);
      for (const item of list) console.log(`  ${item.file ?? item}`);
    }
  }
  console.log();
  console.log(`OK: ${ok}/${total} files matched`);
  console.log(`MISMATCH: ${totalBad}/${total} files`);
  process.exit(totalBad === 0 ? 0 : 1);
} else {
  console.log(`OK: ${ok}/${total} files matched`);
}

function runCompile(fn, source, options) {
  try {
    const result = fn(source, options);
    return {
      kind: 'ok',
      js: result.js?.code ?? '',
      css: result.css?.code ?? '',
      diagnostics: collectErrorDiagnostics(result.warnings)
    };
  } catch (err) {
    return { kind: 'error', message: err?.message ?? String(err), codes: collectCodes(err) };
  }
}

function collectErrorDiagnostics(warnings) {
  const codes = new Set();
  if (Array.isArray(warnings)) {
    for (const w of warnings) {
      if (w?.severity === 'error' && w?.code) codes.add(w.code);
    }
  }
  return codes;
}

function setsEqual(a, b) {
  if (a.size !== b.size) return false;
  for (const v of a) if (!b.has(v)) return false;
  return true;
}

function collectCodes(err) {
  const codes = new Set();
  if (Array.isArray(err?.diagnostics)) {
    for (const d of err.diagnostics) if (d?.code) codes.add(d.code);
  }
  if (err?.code) codes.add(err.code);
  return codes;
}

function errorsParity(ours, theirs) {
  if (ours.kind !== 'error' || theirs.kind !== 'error') return false;
  if (!theirs.codes || theirs.codes.size === 0) return false;
  if (!ours.codes) return false;
  for (const c of theirs.codes) if (!ours.codes.has(c)) return false;
  return true;
}

function stripBanner(code, isModule) {
  if (!isModule) return code;
  return code.replace(VERSION_BANNER, '');
}

async function formatJs(code) {
  if (!code) return '';
  const r = await minify(code, {
    compress: false,
    mangle: false,
    module: true,
    ecma: 2022,
    format: { beautify: true, quote_style: 2, indent_level: 2 }
  });
  return r.code;
}

function formatCss(code) {
  if (!code) return '';
  const { code: out } = lightningTransform({
    filename: 'virtual.css',
    code: Buffer.from(stripLineComments(code)),
    minify: true
  });
  return out.toString('utf8');
}

function canonicalizeInjectedCss(js) {
  if (!js || !js.includes('$$css')) return js;
  let ast;
  try {
    ast = acornParse(js, { ecmaVersion: 'latest', sourceType: 'module' });
  } catch {
    return js;
  }
  const edits = [];
  for (const stmt of ast.body) {
    if (stmt.type !== 'VariableDeclaration') continue;
    for (const decl of stmt.declarations) {
      if (decl.id?.name !== '$$css' || decl.init?.type !== 'ObjectExpression') continue;
      for (const prop of decl.init.properties) {
        const keyName = prop.key?.name ?? prop.key?.value;
        if (keyName !== 'code' || prop.value?.type !== 'Literal') continue;
        if (typeof prop.value.value !== 'string') continue;
        edits.push({ start: prop.value.start, end: prop.value.end, value: prop.value.value });
      }
    }
  }
  if (edits.length === 0) return js;
  edits.sort((a, b) => b.start - a.start);
  let out = js;
  for (const e of edits) {
    out = out.slice(0, e.start) + JSON.stringify(normalizeInjectedCss(e.value)) + out.slice(e.end);
  }
  return out;
}

function normalizeInjectedCss(css) {
  const stripped = css.replace(/\/\*# sourceMappingURL=[\s\S]*$/, '').trimEnd();
  try {
    const { code } = lightningTransform({
      filename: 'virtual.css',
      code: Buffer.from(stripped),
      minify: true
    });
    return code.toString('utf8');
  } catch {
    return stripped.replace(/\s+/g, ' ').trim();
  }
}

function stripLineComments(code) {
  return code.replace(/^[ \t]*\/\/.*$/gm, '');
}

function stripComments(code) {
  const comments = [];
  try {
    acornParse(code, { ecmaVersion: 'latest', sourceType: 'module', onComment: comments });
  } catch {
    return code;
  }
  if (comments.length === 0) return code;
  let out = '';
  let cursor = 0;
  for (const comment of comments) {
    if (comment.start < cursor) continue;
    out += code.slice(cursor, comment.start);
    cursor = comment.end;
  }
  out += code.slice(cursor);
  return out;
}

function formatCodes(codes) {
  if (!codes || codes.size === 0) return '';
  return ` [${[...codes].join(', ')}]`;
}

function errorReason(ours, theirs) {
  if (ours.kind === 'error' && theirs.kind === 'ok') return 'rust-error';
  if (ours.kind === 'ok' && theirs.kind === 'error') return 'reference-error';
  return 'errors-differ';
}

function handleMismatch(file, options, reason, ours, theirs, formatted, formatErr, size = 0, side = null) {
  if (dryRun) {
    buckets[reason].push({ file, size });
    if (printDiffs) printMismatch(file, reason, ours, theirs, formatted, formatErr, side);
    return;
  }
  fail(file, options, reason, ours, theirs, formatted, formatErr, side);
}

async function tryFormatBoth(fn, ours, theirs) {
  let oursOut;
  let theirsOut;
  let oursErr = null;
  let theirsErr = null;
  try { oursOut = await fn(ours); } catch (e) { oursErr = e; }
  try { theirsOut = await fn(theirs); } catch (e) { theirsErr = e; }
  if (oursErr && theirsErr) {
    return { kind: 'both-failed', err: oursErr, side: 'ours+theirs' };
  }
  if (oursErr) return { kind: 'one-failed', err: oursErr, side: 'ours' };
  if (theirsErr) return { kind: 'one-failed', err: theirsErr, side: 'theirs' };
  return { kind: 'ok', ours: oursOut, theirs: theirsOut };
}

function normalizeWs(s) {
  return (s ?? '').replace(/\s+/g, ' ').trim();
}

function printMismatch(file, reason, ours, theirs, formatted, formatErr, side = null) {
  clearProgress();
  console.log();
  console.log(`MISMATCH: ${file}  [${reason}]`);
  if (ours?.kind === 'error') console.log(`rust-error: ${ours.message}${formatCodes(ours.codes)}`);
  if (theirs?.kind === 'error') console.log(`reference-error: ${theirs.message}${formatCodes(theirs.codes)}`);
  if (reason === 'diagnostics-mismatch') {
    console.log(`rust-diagnostics:${formatCodes(ours.diagnostics) || ' (none)'}`);
    console.log(`reference-diagnostics:${formatCodes(theirs.diagnostics) || ' (none)'}`);
  }
  if (formatErr) console.log(`format-error${side ? ` (${side})` : ''}: ${formatErr?.message ?? formatErr}`);
  if (formatted) {
    const patch = createPatch(file, formatted.theirs, formatted.ours, 'reference', 'rust', { context: 3 });
    console.log();
    console.log(patch);
  }
}

function diffSize(a, b) {
  const patch = createPatch('', a ?? '', b ?? '', '', '', { context: 0 });
  let n = 0;
  for (const line of patch.split('\n')) {
    const c0 = line.charCodeAt(0);
    if ((c0 === 43 || c0 === 45) && line.charCodeAt(1) !== c0) n++;
  }
  return n;
}

function sizeBucket(n) {
  if (n <= 2) return 'xs';
  if (n <= 10) return 's';
  if (n <= 50) return 'm';
  if (n <= 200) return 'l';
  return 'xl';
}

function fail(file, options, reason, ours, theirs, formatted, formatErr, side = null) {
  clearProgress();
  console.log(`MISMATCH: ${file}`);
  if (ours.kind === 'error') console.log(`rust-error: ${ours.message}${formatCodes(ours.codes)}`);
  if (theirs.kind === 'error') console.log(`reference-error: ${theirs.message}${formatCodes(theirs.codes)}`);
  if (reason === 'diagnostics-mismatch') {
    console.log(`rust-diagnostics:${formatCodes(ours.diagnostics) || ' (none)'}`);
    console.log(`reference-diagnostics:${formatCodes(theirs.diagnostics) || ' (none)'}`);
  }
  if (formatErr) console.log(`format-error${side ? ` (${side})` : ''}: ${formatErr?.message ?? formatErr}`);
  if (formatted) {
    const patch = createPatch(file, formatted.theirs, formatted.ours, 'reference', 'rust', { context: 3 });
    console.log();
    console.log(colorize(patch));
    console.log();
  }
  console.log(`progress: ${processed}/${total} processed before failure`);
  console.log(`options: ${JSON.stringify(options)}`);
  console.log(`reason: ${reason}`);
  process.exit(1);
}

function reportProgress(done, total, ok, file) {
  if (!isTTY) return;
  const bad = done - ok;
  const line = dryRun
    ? `[${done}/${total}] ok=${ok} bad=${bad} ${file}`
    : `[${done}/${total}] ${file}`;
  process.stdout.write(`\r\x1b[2K${line.slice(0, process.stdout.columns ?? 200)}`);
}

function clearProgress() {
  if (!isTTY) return;
  process.stdout.write('\r\x1b[2K');
}

function colorize(patch) {
  if (!process.stdout.isTTY) return patch;
  const RED = '\x1b[31m';
  const GREEN = '\x1b[32m';
  const CYAN = '\x1b[36m';
  const RESET = '\x1b[0m';
  return patch
    .split('\n')
    .map((line) => {
      if (line.startsWith('+++') || line.startsWith('---')) return `${CYAN}${line}${RESET}`;
      if (line.startsWith('@@')) return `${CYAN}${line}${RESET}`;
      if (line.startsWith('+')) return `${GREEN}${line}${RESET}`;
      if (line.startsWith('-')) return `${RED}${line}${RESET}`;
      return line;
    })
    .join('\n');
}
