#!/usr/bin/env node
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';
import fg from 'fast-glob';
import * as prettier from 'prettier';
import { createPatch } from 'diff';
import { compile as refCompile, compileModule as refCompileModule } from 'svelte/compiler';
import { compile as ourCompile, compileModule as ourCompileModule } from '@mrwaip/svelte-rs2/compiler';

const VERSION_BANNER = /^\/\*.*?generated by Svelte.*?\*\/\n/;

const arg = process.argv[2];
if (!arg) {
  console.error('usage: svelte-rs2-sweep <directory>');
  process.exit(2);
}

const root = resolve(arg);
if (!existsSync(root) || !statSync(root).isDirectory()) {
  console.error(`svelte-rs2-sweep: not a directory: ${root}`);
  process.exit(2);
}

const files = await fg(['**/*.svelte', '**/*.svelte.js', '**/*.svelte.ts'], {
  cwd: root,
  absolute: true,
  onlyFiles: true,
  followSymbolicLinks: false,
  suppressErrors: true
});

if (files.length === 0) {
  console.error(`svelte-rs2-sweep: no svelte files found in ${root}`);
  process.exit(2);
}

files.sort();

const total = files.length;
const isTTY = Boolean(process.stdout.isTTY);
console.log(`found ${total} files`);

let processed = 0;
for (const file of files) {
  reportProgress(processed, total, file);
  const isModule = file.endsWith('.svelte.js') || file.endsWith('.svelte.ts');
  const source = await readFile(file, 'utf8');
  const options = isModule
    ? { dev: false, filename: file }
    : { generate: 'client', dev: false, filename: file, discloseVersion: false, modernAst: true };

  const ours = runCompile(isModule ? ourCompileModule : ourCompile, source, options);
  const theirs = runCompile(isModule ? refCompileModule : refCompile, source, options);

  if (ours.kind === 'error' || theirs.kind === 'error') {
    if (ours.kind === theirs.kind && ours.message === theirs.message) {
      continue;
    }
    fail(file, options, errorReason(ours, theirs), ours, theirs);
  }

  const ourJs = await formatJs(stripBanner(ours.js, isModule));
  const theirJs = await formatJs(stripBanner(theirs.js, isModule));
  if (ourJs !== theirJs) {
    fail(file, options, 'js', ours, theirs, { ours: ourJs, theirs: theirJs });
  }

  const ourCss = await formatCss(ours.css);
  const theirCss = await formatCss(theirs.css);
  if (ourCss !== theirCss) {
    fail(file, options, 'css', ours, theirs, { ours: ourCss, theirs: theirCss });
  }

  processed += 1;
}

clearProgress();
console.log(`OK: ${processed}/${total} files matched`);

function runCompile(fn, source, options) {
  try {
    const result = fn(source, options);
    return { kind: 'ok', js: result.js?.code ?? '', css: result.css?.code ?? '' };
  } catch (err) {
    return { kind: 'error', message: err?.message ?? String(err) };
  }
}

function stripBanner(code, isModule) {
  if (!isModule) return code;
  return code.replace(VERSION_BANNER, '');
}

async function formatJs(code) {
  if (!code) return '';
  return await prettier.format(code, { parser: 'babel' });
}

async function formatCss(code) {
  if (!code) return '';
  return await prettier.format(code, { parser: 'css' });
}

function errorReason(ours, theirs) {
  if (ours.kind === 'error' && theirs.kind === 'ok') return 'rust-error';
  if (ours.kind === 'ok' && theirs.kind === 'error') return 'reference-error';
  return 'errors-differ';
}

function fail(file, options, reason, ours, theirs, formatted) {
  clearProgress();
  console.log(`MISMATCH: ${file}`);
  console.log(`progress: ${processed}/${total} processed before failure`);
  console.log(`options: ${JSON.stringify(options)}`);
  console.log(`reason: ${reason}`);
  if (ours.kind === 'error') console.log(`rust-error: ${ours.message}`);
  if (theirs.kind === 'error') console.log(`reference-error: ${theirs.message}`);
  if (formatted) {
    const patch = createPatch(file, formatted.theirs, formatted.ours, 'reference', 'rust', { context: 3 });
    console.log();
    console.log(colorize(patch));
  }
  process.exit(1);
}

function reportProgress(done, total, file) {
  if (!isTTY) return;
  const line = `[${done}/${total}] ${file}`;
  process.stdout.write(`\r\x1b[2K${line.slice(0, process.stdout.columns ?? 200)}`);
}

function clearProgress() {
  if (!isTTY) return;
  process.stdout.write('\r\x1b[2K');
}

function colorize(patch) {
  if (!process.stdout.isTTY) return patch;
  const RED = '\x1b[31m';
  const GREEN = '\x1b[32m';
  const CYAN = '\x1b[36m';
  const RESET = '\x1b[0m';
  return patch
    .split('\n')
    .map((line) => {
      if (line.startsWith('+++') || line.startsWith('---')) return `${CYAN}${line}${RESET}`;
      if (line.startsWith('@@')) return `${CYAN}${line}${RESET}`;
      if (line.startsWith('+')) return `${GREEN}${line}${RESET}`;
      if (line.startsWith('-')) return `${RED}${line}${RESET}`;
      return line;
    })
    .join('\n');
}
