[package]
name = "svelte-rs-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc_allocator = "0.38.0"
oxc_ast = "0.38.0"
oxc_parser = "0.38.0"
oxc_span = "0.38.0"
rccell = "0.1.3"
