[package]
name = "svelte-rs-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compact_str = "0.8.1"
glob = "0.3.2"
oxc_allocator = "0.44.0"
oxc_ast = "0.44.0"
oxc_codegen = "0.44.0"
oxc_index = "2.0.0"
oxc_parser = "0.44.0"
oxc_semantic = "0.44.0"
oxc_span = "0.44.0"
oxc_transformer = "0.44.0"
oxc_traverse = "0.44.0"
pretty_assertions = "1.4.1"
rccell = "0.1.3"
