[workspace]
members = ["crates/*", "tasks/*"]
resolver = "2"


[workspace.dependencies]
ast = { path = "crates/ast" }
span = { path = "crates/span" }
diagnostics = { path = "crates/diagnostics" }
parser = { path = "crates/parser" }
analyzer = { path = "crates/analyzer" }
transformer = { path = "crates/transformer" }
compiler = { path = "crates/compiler" }
compact_str = "0.8.1"
glob = "0.3.2"
oxc_allocator = "0.44.0"
oxc_ast = "0.44.0"
oxc_codegen = "0.44.0"
oxc_index = "2.0.0"
oxc_parser = "0.44.0"
oxc_semantic = "0.44.0"
oxc_span = "0.44.0"
oxc_transformer = "0.44.0"
oxc_traverse = "0.44.0"
pretty_assertions = "1.4.1"
rccell = "0.1.3"
rstest = "0.24.0"
