import "svelte/internal/flags/legacy";
import * as $ from "svelte/internal/client";
export default function App($$anchor) {
	const $state = () => $.store_get(state, "$state", $$stores);
	const $derived = () => $.store_get(derived, "$derived", $$stores);
	const $props = () => $.store_get(props, "$props", $$stores);
	const $effect = () => $.store_get(effect, "$effect", $$stores);
	const $inspect = () => $.store_get(inspect, "$inspect", $$stores);
	const $bindable = () => $.store_get(bindable, "$bindable", $$stores);
	const [$$stores, $$cleanup] = $.setup_stores();
	let stateBase = 0;
	let derivedBase = 1;
	let propsBase = {};
	let effectFn = () => {};
	let inspectVal = "x";
	let bindableDefault = false;
	let s = $state()(stateBase);
	let r = $state().raw(propsBase);
	let snap = $state().snapshot(propsBase);
	let d = $derived()(derivedBase);
	let db = $derived().by(() => derivedBase);
	let p = $props()();
	let pid = $props().id();
	let t = $effect().tracking();
	$effect()(effectFn);
	$effect().pre(effectFn);
	$inspect()(inspectVal);
	let b = $bindable()(bindableDefault);
	$$cleanup();
}
