/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compile(source: string, options?: NativeCompileOptions | undefined | null): NativeCompileResult

export declare function compileModule(source: string, options?: NativeModuleCompileOptions | undefined | null): NativeCompileResult

export interface NativeCompileOptions {
  dev?: boolean
  filename?: string
  rootDir?: string
  name?: string
  customElement?: boolean
  namespace?: string
  css?: string
  runes?: boolean
  preserveComments?: boolean
  preserveWhitespace?: boolean
  discloseVersion?: boolean
  hmr?: boolean
  accessors?: boolean
  immutable?: boolean
  compatibilityComponentApi?: number
  experimentalAsync?: boolean
  generate?: string
  sourcemap?: string
  suppress?: Array<string>
}

export interface NativeCompileResult {
  js?: NativeJsOutput
  css?: NativeCssOutput
  diagnostics: Array<NativeDiagnostic>
}

export interface NativeCssOutput {
  code: string
  map?: string
  hasGlobal: boolean
}

export interface NativeDiagnostic {
  code: string
  message: string
  severity: string
  startLine: number
  startCol: number
  endLine: number
  endCol: number
  frame?: string
}

export interface NativeJsOutput {
  code: string
  map?: string
}

export interface NativeModuleCompileOptions {
  dev?: boolean
  filename?: string
  rootDir?: string
  generate?: string
  sourcemap?: string
  suppress?: Array<string>
}
