[package]
name = "compiler_tests"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
doctest = false

[[test]]
name = "compiler_tests_v3"
path = "test_v3.rs"

[[test]]
name = "compiler_tests_clusters"
path = "test_clusters.rs"

[[test]]
name = "compiler_tests_sourcemap"
path = "test_sourcemap.rs"

[[test]]
name = "compiler_tests_ssr_smoke"
path = "test_ssr_smoke.rs"

[dependencies]
svelte_compiler = { workspace = true }
svelte_sourcemap = { workspace = true }
serde_json = "1"
pretty_assertions = { workspace = true }
test_support = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
