[package]
name = "svelte_emit_builders"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true }
svelte_analyze = { workspace = true }
svelte_ast_builder = { workspace = true }
svelte_component_semantics = { workspace = true }
