mod async_wrap;
pub(in crate::codegen) use async_wrap::owns_fragment_anchor;
mod await_block;
mod dispatch;
mod each_block;
mod html_tag;
mod if_block;
mod key_block;
pub(crate) mod render_tag;
mod snippet_block;
