#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { compile, compileModule } from "svelte/compiler";
import { stripTypeScriptTypes } from "node:module";
import { transformSync as oxcTransformSync } from "oxc-transform";

function stripTsToJs(source) {
  stripTypeScriptTypes(source, { mode: "strip" });
  return oxcTransformSync("input.ts", source, {
    typescript: { onlyRemoveTypeImports: true },
  }).code;
}

function stripVersionComment(code) {
  return code.replace(/^\/\*.*?generated by Svelte.*?\*\/\n/, "");
}

function collectErrorCodes(warnings) {
  const codes = [];
  if (Array.isArray(warnings)) {
    for (const warning of warnings) {
      if (warning?.severity === "error" && warning?.code) codes.push(warning.code);
    }
  }
  return codes;
}

function collectThrownCodes(err) {
  const codes = [];
  if (Array.isArray(err?.diagnostics)) {
    for (const diagnostic of err.diagnostics) {
      if (diagnostic?.code) codes.push(diagnostic.code);
    }
  }
  if (err?.code) codes.push(err.code);
  return codes;
}

const inputPath = process.env.INPUT_FILE;
if (!inputPath) {
  console.error("sweep reference: INPUT_FILE not set");
  process.exit(2);
}
const files = JSON.parse(readFileSync(inputPath, "utf8"));
const modeConfig = process.env.SWEEP_CONFIG ? JSON.parse(process.env.SWEEP_CONFIG) : {};

const results = {};

for (const file of files) {
  const isModule = file.endsWith(".svelte.js") || file.endsWith(".svelte.ts");
  const isTsModule = file.endsWith(".svelte.ts");

  let source;
  try {
    source = readFileSync(file, "utf8");
  } catch (err) {
    results[file] = { readError: String(err?.message ?? err) };
    continue;
  }

  let moduleSource = source;
  if (isTsModule) {
    try {
      moduleSource = stripTsToJs(source);
    } catch (err) {
      results[file] = { formatError: String(err?.message ?? err) };
      continue;
    }
  }

  const runCell = (dev, generate) => {
    try {
      const result = isModule
        ? compileModule(moduleSource, {
            filename: isTsModule ? "input.svelte.ts" : "input.svelte.js",
            dev,
            ...(generate ? { generate } : {}),
          })
        : compile(source, {
            filename: file,
            name: "App",
            discloseVersion: false,
            modernAst: true,
            dev,
            ...(generate ? { generate } : {}),
            ...modeConfig,
          });
      let js = result.js?.code ?? "";
      if (isModule) js = stripVersionComment(js);
      return { js, css: result.css?.code ?? null, warnings: collectErrorCodes(result.warnings) };
    } catch (err) {
      return { error: String(err?.message ?? err), codes: collectThrownCodes(err) };
    }
  };

  results[file] = {
    clientProd: runCell(false, null),
    clientDev: runCell(true, null),
    serverProd: runCell(false, "server"),
    serverDev: runCell(true, "server"),
  };
}

process.stdout.write(JSON.stringify(results));
