/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare function compile(source: string, options?: NativeCompileOptions | undefined | null): NativeCompileResult

export declare function compileModule(source: string, options?: NativeModuleCompileOptions | undefined | null): NativeCompileResult

export declare function findPreprocessorRegions(source: string): NativePreprocessorRegions

export interface NativeCompileOptions {
  dev?: boolean
  filename?: string
  rootDir?: string
  name?: string
  customElement?: boolean
  namespace?: string
  css?: string
  runes?: boolean
  preserveComments?: boolean
  preserveWhitespace?: boolean
  discloseVersion?: boolean
  hmr?: boolean
  accessors?: boolean
  immutable?: boolean
  compatibilityComponentApi?: number
  experimentalAsync?: boolean
  generate?: string
  sourcemap?: string
  suppress?: Array<string>
}

export interface NativeCompileResult {
  js?: NativeJsOutput
  css?: NativeCssOutput
  diagnostics: Array<NativeDiagnostic>
}

export interface NativeCssOutput {
  code: string
  map?: string
  hasGlobal: boolean
}

export interface NativeDiagnostic {
  code: string
  message: string
  severity: string
  startLine: number
  startCol: number
  endLine: number
  endCol: number
  frame?: string
}

export interface NativeJsOutput {
  code: string
  map?: string
}

export interface NativeModuleCompileOptions {
  dev?: boolean
  filename?: string
  rootDir?: string
  generate?: string
  sourcemap?: string
  suppress?: Array<string>
}

export interface NativePreprocessorRegions {
  instanceScript?: NativeScriptRegion
  moduleScript?: NativeScriptRegion
  style?: NativeTagRegion
}

export interface NativeScriptRegion {
  region: NativeTagRegion
  isTypescript: boolean
  isModule: boolean
}

export interface NativeTagAttribute {
  name: string
  value?: string
}

export interface NativeTagRegion {
  tagStart: number
  tagEnd: number
  contentStart: number
  contentEnd: number
  content: string
  attributes: Array<NativeTagAttribute>
}

export declare function sourceMapToJson(map: ExternalObject<SourceMap>): string

export declare function spliceRegion(document: string, documentMap: ExternalObject<SourceMap> | undefined | null, regionStart: number, regionEnd: number, newContent: string, newContentMap: string | undefined | null, filename: string): object
