use super::*;

compiler_case!(declaration_legacy_alias, "await/declaration/legacy/alias", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_array_hole, "await/declaration/legacy/array_hole", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_array_of_objects, "await/declaration/legacy/array_of_objects", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_array_rest, "await/declaration/legacy/array_rest", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_array_rest_nested, "await/declaration/legacy/array_rest_nested", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_computed_key, "await/declaration/legacy/computed_key", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_default_intermediate_array, "await/declaration/legacy/default_intermediate_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_default_intermediate_object, "await/declaration/legacy/default_intermediate_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_default_leaf_array, "await/declaration/legacy/default_leaf_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_default_leaf_object, "await/declaration/legacy/default_leaf_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_flat_object, "await/declaration/legacy/flat_object");
compiler_case!(declaration_legacy_nested_array, "await/declaration/legacy/nested_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_nested_object, "await/declaration/legacy/nested_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_object_in_array_in_object, "await/declaration/legacy/object_in_array_in_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_object_of_arrays, "await/declaration/legacy/object_of_arrays", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_object_rest, "await/declaration/legacy/object_rest", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_legacy_single_array, "await/declaration/legacy/single_array");
compiler_case!(declaration_legacy_string_key, "await/declaration/legacy/string_key", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_alias, "await/declaration/runes/alias", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_array_hole, "await/declaration/runes/array_hole", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_array_of_objects, "await/declaration/runes/array_of_objects", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_array_rest, "await/declaration/runes/array_rest", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_array_rest_nested, "await/declaration/runes/array_rest_nested", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_computed_key, "await/declaration/runes/computed_key", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_default_intermediate_array, "await/declaration/runes/default_intermediate_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_default_intermediate_object, "await/declaration/runes/default_intermediate_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_default_leaf_array, "await/declaration/runes/default_leaf_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_default_leaf_object, "await/declaration/runes/default_leaf_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_flat_object, "await/declaration/runes/flat_object");
compiler_case!(declaration_runes_nested_array, "await/declaration/runes/nested_array", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_nested_object, "await/declaration/runes/nested_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_object_in_array_in_object, "await/declaration/runes/object_in_array_in_object", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_object_of_arrays, "await/declaration/runes/object_of_arrays", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_object_rest, "await/declaration/runes/object_rest", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
compiler_case!(declaration_runes_single_array, "await/declaration/runes/single_array");
compiler_case!(declaration_runes_string_key, "await/declaration/runes/string_key", ignore = "binding-pattern-routing slice 3 (await value/error, codegen) · tag binding-pattern-routing#3");
