use super::*;

compiler_case!(
    const_tag_value_known_shorthand,
    "component_props/const_tag_value_known_shorthand",
    [prod, dev, ssr, ssr_dev]
);
compiler_case!(
    const_tag_shorthand_guard,
    "component_props/const_tag_shorthand_guard",
    [prod, dev, ssr, ssr_dev]
);
compiler_case!(
    exported_fn_prop_inline,
    "component_props/exported_fn_prop_inline"
);
compiler_case!(
    exported_const_prop_inline,
    "component_props/exported_const_prop_inline"
);
compiler_case!(
    css_props_static_guard,
    "component_props/css_props_static_guard"
);
compiler_case!(
    state_literal_shorthand,
    "component_props/state_literal_shorthand"
);
compiler_case!(
    state_reassigned_getter,
    "component_props/state_reassigned_getter"
);
compiler_case!(const_call_getter, "component_props/const_call_getter");
compiler_case!(derived_getter, "component_props/derived_getter");
compiler_case!(
    state_object_never_written,
    "component_props/state_object_never_written"
);
compiler_case!(
    state_function_getter,
    "component_props/state_function_getter"
);
compiler_case!(
    literal_const_shorthand,
    "component_props/literal_const_shorthand"
);
compiler_case!(
    function_const_shorthand,
    "component_props/function_const_shorthand"
);
compiler_case!(
    snippet_shorthand_getter,
    "component_props/snippet_shorthand_getter"
);
compiler_case!(
    call_pure_global_inline,
    "component_props/call_pure_global_inline"
);
compiler_case!(
    call_local_fn_derived,
    "component_props/call_local_fn_derived"
);
compiler_case!(
    call_pure_callee_state_arg_derived,
    "component_props/call_pure_callee_state_arg_derived"
);
compiler_case!(
    call_pure_global_nested_inline,
    "component_props/call_pure_global_nested_inline"
);
compiler_case!(
    each_index_concat_unkeyed,
    "component_props/each_index_concat_unkeyed"
);
compiler_case!(
    each_index_concat_keyed_guard,
    "component_props/each_index_concat_keyed_guard"
);
compiler_case!(
    each_item_concat_guard,
    "component_props/each_item_concat_guard"
);
compiler_case!(
    bind_member_path_legacy_prop_ownership,
    "component_props/bind_member_path_legacy_prop_ownership"
);
compiler_case!(
    bind_member_path_plain_prop_ownership,
    "component_props/bind_member_path_plain_prop_ownership"
);
compiler_case!(
    bind_member_path_slot_index_ownership,
    "component_props/bind_member_path_slot_index_ownership"
);
compiler_case!(
    bind_member_path_const_index_guard,
    "component_props/bind_member_path_const_index_guard"
);
compiler_case!(
    bind_function_pair_prop_name_no_ownership,
    "component_props/bind_function_pair_prop_name_no_ownership"
);
compiler_case!(
    prop_member_mutation_stmt_plain_guard,
    "component_props/prop_member_mutation_stmt_plain_guard"
);
compiler_case!(
    prop_member_mutation_expr_assign,
    "component_props/prop_member_mutation_expr_assign"
);
compiler_case!(
    bind_prop_each_item_member_validate,
    "component_props/bind_prop_each_item_member_validate"
);
compiler_case!(
    bind_prop_store_each_mark_store,
    "component_props/bind_prop_store_each_mark_store"
);
compiler_case!(
    prop_function_alias_getter,
    "component_props/prop_function_alias_getter"
);
compiler_case!(
    prop_function_literal_static_guard,
    "component_props/prop_function_literal_static_guard"
);
compiler_case!(
    prop_unmutated_state_undefined_static,
    "component_props/prop_unmutated_state_undefined_static"
);
compiler_case!(
    bind_store_member_no_ownership,
    "component_props/bind_store_member_no_ownership"
);

compiler_case!(
    reexport_prop_no_default,
    "component_props/reexport_prop_no_default"
);
compiler_case!(
    reexport_prop_with_sibling_default,
    "component_props/reexport_prop_with_sibling_default"
);
compiler_case!(
    reexport_prop_aliased,
    "component_props/reexport_prop_aliased"
);
compiler_case!(
    reexport_bindable_no_default,
    "component_props/reexport_bindable_no_default"
);
compiler_case!(
    reexport_prop_default_guard,
    "component_props/reexport_prop_default_guard"
);
compiler_case!(
    reexport_prop_mutated_guard,
    "component_props/reexport_prop_mutated_guard"
);
compiler_case!(
    prop_no_export_inline_guard,
    "component_props/prop_no_export_inline_guard"
);
compiler_case!(
    accessors_option_export_let_guard,
    "component_props/accessors_option_export_let_guard"
);
