use super::*;

compiler_case!(
    declaration_legacy_alias,
    "const_tag/declaration/legacy/alias"
);
compiler_case!(
    declaration_legacy_array_hole,
    "const_tag/declaration/legacy/array_hole"
);
compiler_case!(
    declaration_legacy_array_of_objects,
    "const_tag/declaration/legacy/array_of_objects"
);
compiler_case!(
    declaration_legacy_array_rest,
    "const_tag/declaration/legacy/array_rest"
);
compiler_case!(
    declaration_legacy_array_rest_nested,
    "const_tag/declaration/legacy/array_rest_nested"
);
compiler_case!(
    declaration_legacy_computed_key,
    "const_tag/declaration/legacy/computed_key"
);
compiler_case!(
    declaration_legacy_computed_key_self_ref,
    "const_tag/declaration/legacy/computed_key_self_ref"
);
compiler_case!(
    declaration_legacy_default_intermediate_array,
    "const_tag/declaration/legacy/default_intermediate_array"
);
compiler_case!(
    declaration_legacy_default_intermediate_object,
    "const_tag/declaration/legacy/default_intermediate_object"
);
compiler_case!(
    declaration_legacy_default_leaf_array,
    "const_tag/declaration/legacy/default_leaf_array"
);
compiler_case!(
    declaration_legacy_default_leaf_object,
    "const_tag/declaration/legacy/default_leaf_object"
);
compiler_case!(
    declaration_legacy_flat_object,
    "const_tag/declaration/legacy/flat_object"
);
compiler_case!(
    declaration_legacy_nested_array,
    "const_tag/declaration/legacy/nested_array"
);
compiler_case!(
    declaration_legacy_nested_object,
    "const_tag/declaration/legacy/nested_object"
);
compiler_case!(
    declaration_legacy_object_in_array_in_object,
    "const_tag/declaration/legacy/object_in_array_in_object"
);
compiler_case!(
    declaration_legacy_object_of_arrays,
    "const_tag/declaration/legacy/object_of_arrays"
);
compiler_case!(
    declaration_legacy_object_rest,
    "const_tag/declaration/legacy/object_rest"
);
compiler_case!(
    declaration_legacy_single_array,
    "const_tag/declaration/legacy/single_array"
);
compiler_case!(
    declaration_legacy_string_key,
    "const_tag/declaration/legacy/string_key"
);
compiler_case!(declaration_runes_alias, "const_tag/declaration/runes/alias");
compiler_case!(
    declaration_runes_array_hole,
    "const_tag/declaration/runes/array_hole"
);
compiler_case!(
    declaration_runes_array_of_objects,
    "const_tag/declaration/runes/array_of_objects"
);
compiler_case!(
    declaration_runes_array_rest,
    "const_tag/declaration/runes/array_rest"
);
compiler_case!(
    declaration_runes_array_rest_nested,
    "const_tag/declaration/runes/array_rest_nested"
);
compiler_case!(
    declaration_runes_computed_key,
    "const_tag/declaration/runes/computed_key"
);
compiler_case!(
    declaration_runes_default_intermediate_array,
    "const_tag/declaration/runes/default_intermediate_array"
);
compiler_case!(
    declaration_runes_default_intermediate_object,
    "const_tag/declaration/runes/default_intermediate_object"
);
compiler_case!(
    declaration_runes_default_leaf_array,
    "const_tag/declaration/runes/default_leaf_array"
);
compiler_case!(
    declaration_runes_default_leaf_object,
    "const_tag/declaration/runes/default_leaf_object"
);
compiler_case!(
    declaration_runes_flat_object,
    "const_tag/declaration/runes/flat_object"
);
compiler_case!(
    declaration_runes_nested_array,
    "const_tag/declaration/runes/nested_array"
);
compiler_case!(
    declaration_runes_nested_object,
    "const_tag/declaration/runes/nested_object"
);
compiler_case!(
    declaration_runes_object_in_array_in_object,
    "const_tag/declaration/runes/object_in_array_in_object"
);
compiler_case!(
    declaration_runes_object_of_arrays,
    "const_tag/declaration/runes/object_of_arrays"
);
compiler_case!(
    declaration_runes_object_rest,
    "const_tag/declaration/runes/object_rest"
);
compiler_case!(
    declaration_runes_single_array,
    "const_tag/declaration/runes/single_array"
);
compiler_case!(
    declaration_runes_string_key,
    "const_tag/declaration/runes/string_key"
);
compiler_case!(
    order_legacy_forward_dependency,
    "const_tag/order/legacy/forward_dependency"
);
compiler_case!(order_legacy_deep_chain, "const_tag/order/legacy/deep_chain");
compiler_case!(
    order_legacy_forward_reactive,
    "const_tag/order/legacy/forward_reactive"
);
compiler_case!(
    order_legacy_in_order_guard,
    "const_tag/order/legacy/in_order_guard"
);
compiler_case!(
    order_legacy_independent_guard,
    "const_tag/order/legacy/independent_guard"
);
compiler_case!(
    order_legacy_single_guard,
    "const_tag/order/legacy/single_guard"
);
compiler_case!(
    order_runes_in_order_guard,
    "const_tag/order/runes/in_order_guard"
);
