use super::*;

compiler_case!(declaration_legacy_alias, "each/declaration/legacy/alias");
compiler_case!(
    declaration_legacy_array_hole,
    "each/declaration/legacy/array_hole"
);
compiler_case!(
    declaration_legacy_array_of_objects,
    "each/declaration/legacy/array_of_objects"
);
compiler_case!(
    declaration_legacy_array_rest,
    "each/declaration/legacy/array_rest"
);
compiler_case!(
    declaration_legacy_array_rest_nested,
    "each/declaration/legacy/array_rest_nested"
);
compiler_case!(
    declaration_legacy_computed_key,
    "each/declaration/legacy/computed_key"
);
compiler_case!(
    declaration_legacy_computed_key_sibling_ref,
    "each/declaration/legacy/computed_key_sibling_ref"
);
compiler_case!(
    declaration_legacy_computed_key_prop_ref,
    "each/declaration/legacy/computed_key_prop_ref"
);
compiler_case!(
    declaration_legacy_default_value_sibling_ref,
    "each/declaration/legacy/default_value_sibling_ref"
);
compiler_case!(
    declaration_legacy_default_intermediate_array,
    "each/declaration/legacy/default_intermediate_array"
);
compiler_case!(
    declaration_legacy_default_intermediate_object,
    "each/declaration/legacy/default_intermediate_object"
);
compiler_case!(
    declaration_legacy_default_leaf_array,
    "each/declaration/legacy/default_leaf_array"
);
compiler_case!(
    declaration_legacy_default_leaf_object,
    "each/declaration/legacy/default_leaf_object"
);
compiler_case!(
    declaration_legacy_flat_object,
    "each/declaration/legacy/flat_object"
);
compiler_case!(
    declaration_legacy_nested_array,
    "each/declaration/legacy/nested_array"
);
compiler_case!(
    declaration_legacy_nested_object,
    "each/declaration/legacy/nested_object"
);
compiler_case!(
    declaration_legacy_object_in_array_in_object,
    "each/declaration/legacy/object_in_array_in_object"
);
compiler_case!(
    declaration_legacy_object_of_arrays,
    "each/declaration/legacy/object_of_arrays"
);
compiler_case!(
    declaration_legacy_object_rest,
    "each/declaration/legacy/object_rest"
);
compiler_case!(
    declaration_legacy_single_array,
    "each/declaration/legacy/single_array"
);
compiler_case!(
    declaration_legacy_string_key,
    "each/declaration/legacy/string_key"
);
compiler_case!(declaration_runes_alias, "each/declaration/runes/alias");
compiler_case!(
    declaration_runes_array_hole,
    "each/declaration/runes/array_hole"
);
compiler_case!(
    declaration_runes_array_of_objects,
    "each/declaration/runes/array_of_objects"
);
compiler_case!(
    declaration_runes_array_rest,
    "each/declaration/runes/array_rest"
);
compiler_case!(
    declaration_runes_array_rest_nested,
    "each/declaration/runes/array_rest_nested"
);
compiler_case!(
    declaration_runes_computed_key,
    "each/declaration/runes/computed_key"
);
compiler_case!(
    declaration_runes_default_intermediate_array,
    "each/declaration/runes/default_intermediate_array"
);
compiler_case!(
    declaration_runes_default_intermediate_object,
    "each/declaration/runes/default_intermediate_object"
);
compiler_case!(
    declaration_runes_default_leaf_array,
    "each/declaration/runes/default_leaf_array"
);
compiler_case!(
    declaration_runes_default_leaf_object,
    "each/declaration/runes/default_leaf_object"
);
compiler_case!(
    declaration_runes_flat_object,
    "each/declaration/runes/flat_object"
);
compiler_case!(
    declaration_runes_nested_array,
    "each/declaration/runes/nested_array"
);
compiler_case!(
    declaration_runes_nested_object,
    "each/declaration/runes/nested_object"
);
compiler_case!(
    declaration_runes_object_in_array_in_object,
    "each/declaration/runes/object_in_array_in_object"
);
compiler_case!(
    declaration_runes_object_of_arrays,
    "each/declaration/runes/object_of_arrays"
);
compiler_case!(
    declaration_runes_object_rest,
    "each/declaration/runes/object_rest"
);
compiler_case!(
    declaration_runes_single_array,
    "each/declaration/runes/single_array"
);
compiler_case!(
    declaration_runes_string_key,
    "each/declaration/runes/string_key"
);
