use super::*;

compiler_case!(
    key_equals_index_no_context,
    "each/key_equals_index_no_context"
);
compiler_case!(declaration_legacy_alias, "each/declaration/legacy/alias");
compiler_case!(
    declaration_legacy_array_hole,
    "each/declaration/legacy/array_hole"
);
compiler_case!(
    declaration_legacy_array_of_objects,
    "each/declaration/legacy/array_of_objects"
);
compiler_case!(
    declaration_legacy_array_rest,
    "each/declaration/legacy/array_rest"
);
compiler_case!(
    declaration_legacy_array_rest_nested,
    "each/declaration/legacy/array_rest_nested"
);
compiler_case!(
    declaration_legacy_computed_key,
    "each/declaration/legacy/computed_key"
);
compiler_case!(
    declaration_legacy_computed_key_sibling_ref,
    "each/declaration/legacy/computed_key_sibling_ref"
);
compiler_case!(
    declaration_legacy_computed_key_prop_ref,
    "each/declaration/legacy/computed_key_prop_ref"
);
compiler_case!(
    declaration_legacy_default_value_sibling_ref,
    "each/declaration/legacy/default_value_sibling_ref"
);
compiler_case!(
    declaration_legacy_default_value_binary_sibling,
    "each/declaration/legacy/default_value_binary_sibling"
);
compiler_case!(
    declaration_legacy_default_value_ident_sibling,
    "each/declaration/legacy/default_value_ident_sibling"
);
compiler_case!(
    declaration_legacy_unkeyed_index_component_prop,
    "each/declaration/legacy/unkeyed_index_component_prop"
);
compiler_case!(
    declaration_legacy_item_closure_component_prop,
    "each/declaration/legacy/item_closure_component_prop"
);
compiler_case!(
    declaration_legacy_import_collection,
    "each/declaration/legacy/import_collection"
);
compiler_case!(
    declaration_legacy_default_intermediate_array,
    "each/declaration/legacy/default_intermediate_array"
);
compiler_case!(
    declaration_legacy_default_intermediate_object,
    "each/declaration/legacy/default_intermediate_object"
);
compiler_case!(
    declaration_legacy_default_leaf_array,
    "each/declaration/legacy/default_leaf_array"
);
compiler_case!(
    declaration_legacy_default_leaf_object,
    "each/declaration/legacy/default_leaf_object"
);
compiler_case!(
    declaration_legacy_flat_object,
    "each/declaration/legacy/flat_object"
);
compiler_case!(
    declaration_legacy_nested_array,
    "each/declaration/legacy/nested_array"
);
compiler_case!(
    declaration_legacy_nested_object,
    "each/declaration/legacy/nested_object"
);
compiler_case!(
    declaration_legacy_object_in_array_in_object,
    "each/declaration/legacy/object_in_array_in_object"
);
compiler_case!(
    declaration_legacy_object_of_arrays,
    "each/declaration/legacy/object_of_arrays"
);
compiler_case!(
    declaration_legacy_object_rest,
    "each/declaration/legacy/object_rest"
);
compiler_case!(
    declaration_legacy_single_array,
    "each/declaration/legacy/single_array"
);
compiler_case!(
    declaration_legacy_string_key,
    "each/declaration/legacy/string_key"
);
compiler_case!(declaration_runes_alias, "each/declaration/runes/alias");
compiler_case!(
    declaration_runes_import_collection,
    "each/declaration/runes/import_collection"
);
compiler_case!(
    declaration_runes_array_hole,
    "each/declaration/runes/array_hole"
);
compiler_case!(
    declaration_runes_array_of_objects,
    "each/declaration/runes/array_of_objects"
);
compiler_case!(
    declaration_runes_array_rest,
    "each/declaration/runes/array_rest"
);
compiler_case!(
    declaration_runes_array_rest_nested,
    "each/declaration/runes/array_rest_nested"
);
compiler_case!(
    declaration_runes_computed_key,
    "each/declaration/runes/computed_key"
);
compiler_case!(
    declaration_runes_default_intermediate_array,
    "each/declaration/runes/default_intermediate_array"
);
compiler_case!(
    declaration_runes_default_intermediate_object,
    "each/declaration/runes/default_intermediate_object"
);
compiler_case!(
    declaration_runes_default_leaf_array,
    "each/declaration/runes/default_leaf_array"
);
compiler_case!(
    declaration_runes_default_leaf_object,
    "each/declaration/runes/default_leaf_object"
);
compiler_case!(
    declaration_runes_flat_object,
    "each/declaration/runes/flat_object"
);
compiler_case!(
    declaration_runes_nested_array,
    "each/declaration/runes/nested_array"
);
compiler_case!(
    declaration_runes_nested_object,
    "each/declaration/runes/nested_object"
);
compiler_case!(
    declaration_runes_object_in_array_in_object,
    "each/declaration/runes/object_in_array_in_object"
);
compiler_case!(
    declaration_runes_object_of_arrays,
    "each/declaration/runes/object_of_arrays"
);
compiler_case!(
    declaration_runes_object_rest,
    "each/declaration/runes/object_rest"
);
compiler_case!(
    declaration_runes_single_array,
    "each/declaration/runes/single_array"
);
compiler_case!(
    declaration_runes_string_key,
    "each/declaration/runes/string_key"
);

compiler_case!(
    kiw_sample_keyed_item_bind,
    "each/keyed_index_writeback/legacy/sample_keyed_item_bind"
);
compiler_case!(
    kiw_keyed_item_no_bind,
    "each/keyed_index_writeback/legacy/keyed_item_no_bind"
);
compiler_case!(
    kiw_keyed_item_member_bind,
    "each/keyed_index_writeback/legacy/keyed_item_member_bind"
);
compiler_case!(
    kiw_unkeyed_item_bind_guard,
    "each/keyed_index_writeback/legacy/unkeyed_item_bind_guard"
);
compiler_case!(
    kiw_keyed_by_index_guard,
    "each/keyed_index_writeback/legacy/keyed_by_index_guard"
);

compiler_case!(typed_context_typed_ident, "each/typed_context/typed_ident");
compiler_case!(
    typed_context_typed_ident_index,
    "each/typed_context/typed_ident_index"
);
compiler_case!(
    typed_context_plain_ident_guard,
    "each/typed_context/plain_ident_guard"
);
compiler_case!(
    typed_context_plain_ident_index_guard,
    "each/typed_context/plain_ident_index_guard"
);
compiler_case!(
    typed_context_typed_object_guard,
    "each/typed_context/typed_object_guard"
);
compiler_case!(
    typed_context_typed_array_guard,
    "each/typed_context/typed_array_guard"
);

compiler_case!(
    render_index_param_key_is_item_member_mutation,
    "each/render_index_param/runes/key_is_item_member_mutation"
);
compiler_case!(
    render_index_param_key_is_item_no_mutation_guard,
    "each/render_index_param/runes/key_is_item_no_mutation_guard"
);
compiler_case!(
    render_index_param_reactive_item_member_mutation_guard,
    "each/render_index_param/runes/reactive_item_member_mutation_guard"
);
compiler_case!(
    render_index_param_pattern_member_mutation_guard,
    "each/render_index_param/runes/pattern_member_mutation_guard"
);

compiler_case!(
    server_array_name_order,
    "each/server_array_name_order",
    [prod, dev, ssr, ssr_dev]
);
compiler_case!(
    declaration_legacy_static_call_collection_untrack,
    "each/declaration/legacy/static_call_collection_untrack"
);
compiler_case!(
    declaration_legacy_static_literal_collection_guard,
    "each/declaration/legacy/static_literal_collection_guard"
);
compiler_case!(
    nonkeyed_index_binary_prop_static,
    "each/nonkeyed_index_binary_prop_static"
);
compiler_case!(
    legacy_store_member_component_bind_writeback,
    "each/legacy_store_member_component_bind_writeback"
);
compiler_case!(
    keyed_key_is_item_store_collection_reactive,
    "each/keyed_key_is_item_store_collection_reactive"
);
compiler_case!(
    keyed_key_is_item_prop_collection_immutable_guard,
    "each/keyed_key_is_item_prop_collection_immutable_guard"
);
compiler_case!(
    animate_declaration_tag_sibling,
    "each/animate_declaration_tag_sibling",
    [prod, dev, ssr, ssr_dev]
);

compiler_case!(
    async_fallback,
    "each/async_fallback",
    [prod, dev, ssr, ssr_dev]
);
compiler_case!(
    async_deferred_collection,
    "each/async_deferred_collection",
    [prod, dev, ssr, ssr_dev]
);

compiler_case!(
    fallback_const_scope,
    "each/fallback_const_scope",
    [prod, dev, ssr, ssr_dev]
);

compiler_case!(
    nested_each_in_fallback,
    "each/nested_each_in_fallback",
    [prod, dev, ssr, ssr_dev]
);
