use super::*;

compiler_case!(
    array_props,
    "legacy_specifier_destructure_props/array_props"
);
compiler_case!(
    guard_const_destructure_export,
    "legacy_specifier_destructure_props/guard_const_destructure_export"
);
compiler_case!(
    guard_inline_export_destructure,
    "legacy_specifier_destructure_props/guard_inline_export_destructure"
);
compiler_case!(
    guard_simple_specifier,
    "legacy_specifier_destructure_props/guard_simple_specifier"
);
compiler_case!(nested, "legacy_specifier_destructure_props/nested");
compiler_case!(
    object_all_props,
    "legacy_specifier_destructure_props/object_all_props"
);
compiler_case!(
    object_prop_plain,
    "legacy_specifier_destructure_props/object_prop_plain"
);
compiler_case!(
    object_prop_plain_nomut,
    "legacy_specifier_destructure_props/object_prop_plain_nomut"
);
compiler_case!(
    object_prop_state_leaf,
    "legacy_specifier_destructure_props/object_prop_state_leaf"
);
compiler_case!(
    object_prop_store,
    "legacy_specifier_destructure_props/object_prop_store"
);
compiler_case!(
    object_prop_store_nomut,
    "legacy_specifier_destructure_props/object_prop_store_nomut"
);
compiler_case!(
    object_rest,
    "legacy_specifier_destructure_props/object_rest"
);
