use super::*;

compiler_case!(
    declaration_child_alias_weird_sample,
    "legacy/props/declaration/child_alias_weird_sample"
);
compiler_case!(
    declaration_gibberish_key_default_source,
    "legacy/props/declaration/gibberish_key_default_source"
);
compiler_case!(
    declaration_gibberish_key_nonsource,
    "legacy/props/declaration/gibberish_key_nonsource"
);
compiler_case!(
    declaration_identifier_key_nonsource_guard,
    "legacy/props/declaration/identifier_key_nonsource_guard"
);
compiler_case!(
    declaration_main_alias_weird_sample,
    "legacy/props/declaration/main_alias_weird_sample"
);
compiler_case!(
    declaration_nested_array_props,
    "legacy/props/declaration/nested_array_props"
);
compiler_case!(
    declaration_numeric_key_default_source,
    "legacy/props/declaration/numeric_key_default_source"
);
compiler_case!(
    declaration_numeric_key_nonsource,
    "legacy/props/declaration/numeric_key_nonsource"
);
compiler_case!(
    declaration_numeric_key_rest_after,
    "legacy/props/declaration/numeric_key_rest_after"
);
compiler_case!(
    declaration_shorthand_nonsource_guard,
    "legacy/props/declaration/shorthand_nonsource_guard"
);
compiler_case!(
    declaration_string_valid_ident_nonsource_guard,
    "legacy/props/declaration/string_valid_ident_nonsource_guard"
);

compiler_case!(declaration_alias, "legacy/props/declaration/alias");
compiler_case!(
    declaration_array_hole,
    "legacy/props/declaration/array_hole"
);
compiler_case!(
    declaration_array_of_objects,
    "legacy/props/declaration/array_of_objects"
);
compiler_case!(
    declaration_array_rest,
    "legacy/props/declaration/array_rest"
);
compiler_case!(
    declaration_array_rest_nested,
    "legacy/props/declaration/array_rest_nested"
);
compiler_case!(
    declaration_computed_key,
    "legacy/props/declaration/computed_key"
);
compiler_case!(
    declaration_default_intermediate_array,
    "legacy/props/declaration/default_intermediate_array"
);
compiler_case!(
    declaration_default_intermediate_object,
    "legacy/props/declaration/default_intermediate_object"
);
compiler_case!(
    declaration_default_leaf_array,
    "legacy/props/declaration/default_leaf_array"
);
compiler_case!(
    declaration_default_leaf_object,
    "legacy/props/declaration/default_leaf_object"
);
compiler_case!(
    declaration_flat_object,
    "legacy/props/declaration/flat_object"
);
compiler_case!(
    declaration_nested_array,
    "legacy/props/declaration/nested_array"
);
compiler_case!(
    declaration_nested_object,
    "legacy/props/declaration/nested_object"
);
compiler_case!(
    declaration_object_in_array_in_object,
    "legacy/props/declaration/object_in_array_in_object"
);
compiler_case!(
    declaration_object_of_arrays,
    "legacy/props/declaration/object_of_arrays"
);
compiler_case!(
    declaration_object_rest,
    "legacy/props/declaration/object_rest"
);
compiler_case!(
    declaration_single_array,
    "legacy/props/declaration/single_array"
);
compiler_case!(
    declaration_string_key,
    "legacy/props/declaration/string_key"
);
compiler_case!(default_store_autosub, "legacy/props/default/store_autosub");
compiler_case!(
    default_store_in_binary,
    "legacy/props/default/store_in_binary"
);
compiler_case!(
    default_store_in_conditional,
    "legacy/props/default/store_in_conditional"
);
compiler_case!(
    default_guard_literal_eager,
    "legacy/props/default/guard_literal_eager"
);
compiler_case!(
    default_guard_bare_call,
    "legacy/props/default/guard_bare_call"
);
compiler_case!(
    default_guard_member_thunk,
    "legacy/props/default/guard_member_thunk"
);
compiler_case!(
    default_guard_legacy_prop_ref,
    "legacy/props/default/guard_legacy_prop_ref"
);
compiler_case!(
    default_guard_no_default,
    "legacy/props/default/guard_no_default"
);

compiler_case!(
    export_specifier_declaration_order,
    "legacy_props/export_specifier_declaration_order"
);
