use super::*;

compiler_case!(
    assignment_array_default,
    "legacy/state/assignment/array_default"
);
compiler_case!(assignment_array_rest, "legacy/state/assignment/array_rest");
compiler_case!(
    assignment_async_value,
    "legacy/state/assignment/async_value"
);
compiler_case!(
    assignment_basic_array,
    "legacy/state/assignment/basic_array"
);
compiler_case!(
    assignment_computed_key,
    "legacy/state/assignment/computed_key"
);
compiler_case!(
    assignment_expression_position,
    "legacy/state/assignment/expression_position"
);
compiler_case!(
    assignment_guard_nonreactive_locals,
    "legacy/state/assignment/guard_nonreactive_locals"
);
compiler_case!(
    assignment_nested_pattern,
    "legacy/state/assignment/nested_pattern"
);
compiler_case!(
    assignment_nested_rest_pattern,
    "legacy/state/assignment/nested_rest_pattern"
);
compiler_case!(
    assignment_object_ident_rhs,
    "legacy/state/assignment/object_ident_rhs"
);
compiler_case!(
    assignment_object_literal_rhs,
    "legacy/state/assignment/object_literal_rhs"
);
compiler_case!(
    assignment_object_rest,
    "legacy/state/assignment/object_rest"
);
compiler_case!(
    assignment_member_array,
    "legacy/state/assignment/member_array"
);
compiler_case!(
    assignment_member_array_default,
    "legacy/state/assignment/member_array_default"
);
compiler_case!(
    assignment_member_object,
    "legacy/state/assignment/member_object"
);
compiler_case!(
    assignment_member_nonreactive_guard,
    "legacy/state/assignment/member_nonreactive_guard"
);
compiler_case!(
    assignment_member_template_handler,
    "legacy/state/assignment/member_template_handler"
);
compiler_case!(declaration_alias, "legacy/state/declaration/alias");
compiler_case!(
    declaration_array_hole,
    "legacy/state/declaration/array_hole"
);
compiler_case!(
    declaration_array_of_objects,
    "legacy/state/declaration/array_of_objects"
);
compiler_case!(
    declaration_array_rest,
    "legacy/state/declaration/array_rest"
);
compiler_case!(
    declaration_array_rest_nested,
    "legacy/state/declaration/array_rest_nested"
);
compiler_case!(
    declaration_computed_key,
    "legacy/state/declaration/computed_key"
);
compiler_case!(
    declaration_default_intermediate_array,
    "legacy/state/declaration/default_intermediate_array"
);
compiler_case!(
    declaration_default_intermediate_object,
    "legacy/state/declaration/default_intermediate_object"
);
compiler_case!(
    declaration_default_leaf_array,
    "legacy/state/declaration/default_leaf_array"
);
compiler_case!(
    declaration_default_leaf_object,
    "legacy/state/declaration/default_leaf_object"
);
compiler_case!(
    declaration_flat_object,
    "legacy/state/declaration/flat_object"
);
compiler_case!(
    declaration_nested_array,
    "legacy/state/declaration/nested_array"
);
compiler_case!(
    declaration_nested_object,
    "legacy/state/declaration/nested_object"
);
compiler_case!(
    declaration_object_in_array_in_object,
    "legacy/state/declaration/object_in_array_in_object"
);
compiler_case!(
    declaration_object_of_arrays,
    "legacy/state/declaration/object_of_arrays"
);
compiler_case!(
    declaration_object_rest,
    "legacy/state/declaration/object_rest"
);
compiler_case!(
    declaration_single_array,
    "legacy/state/declaration/single_array"
);
compiler_case!(
    declaration_string_key,
    "legacy/state/declaration/string_key"
);
compiler_case!(
    const_member_mutated_handler_only,
    "legacy/state/const_member_mutated_handler_only"
);
compiler_case!(
    const_member_mutated_read_guard,
    "legacy/state/const_member_mutated_read_guard"
);
compiler_case!(
    let_member_mutated_read_guard,
    "legacy/state/let_member_mutated_read_guard"
);
