use super::*;

compiler_case!(
    local_expr_position_dev,
    "member_assign/local_expr_position_dev"
);
compiler_case!(
    local_stmt_position_guard,
    "member_assign/local_stmt_position_guard"
);
compiler_case!(
    legacy_local_expr_position_dev,
    "member_assign/legacy_local_expr_position_dev"
);
compiler_case!(
    this_member_expr_guard,
    "member_assign/this_member_expr_guard"
);
compiler_case!(
    attach_member_rhs_expr_dev,
    "member_assign/attach_member_rhs_expr_dev"
);
compiler_case!(
    attach_prop_rhs_expr_dev,
    "member_assign/attach_prop_rhs_expr_dev"
);
compiler_case!(
    state_proxy_logical_expr_dev,
    "member_assign/state_proxy_logical_expr_dev"
);
compiler_case!(primitive_rhs_guard, "member_assign/primitive_rhs_guard");
compiler_case!(
    event_handler_arrow_guard,
    "member_assign/event_handler_arrow_guard"
);
compiler_case!(
    conditional_primitive_rhs_guard,
    "member_assign/conditional_primitive_rhs_guard"
);
compiler_case!(
    global_root_expr_guard,
    "member_assign/global_root_expr_guard"
);

compiler_case!(
    svelte_element_event_arrow_guard,
    "member_assign/svelte_element_event_arrow_guard"
);
compiler_case!(
    bind_setter_arrow_guard,
    "member_assign/bind_setter_arrow_guard"
);
compiler_case!(
    component_bind_setter_arrow_guard,
    "member_assign/component_bind_setter_arrow_guard"
);
compiler_case!(
    component_prop_assign_guard,
    "member_assign/component_prop_assign_guard"
);
compiler_case!(
    svelte_component_prop_arrow_guard,
    "member_assign/svelte_component_prop_arrow_guard"
);
compiler_case!(
    component_self_prop_arrow_guard,
    "member_assign/component_self_prop_arrow_guard"
);
compiler_case!(component_prop_arrow, "member_assign/component_prop_arrow");
compiler_case!(
    component_prop_arrow_static,
    "member_assign/component_prop_arrow_static"
);
