use super::*;

compiler_case!(
    declaration_nested_function_sync,
    "runes/derived/declaration/nested_function_sync"
);
compiler_case!(
    declaration_nested_effect_sync,
    "runes/derived/declaration/nested_effect_sync"
);
compiler_case!(
    declaration_nested_effect_root_sync,
    "runes/derived/declaration/nested_effect_root_sync"
);
compiler_case!(
    declaration_nested_function_derived_by,
    "runes/derived/declaration/nested_function_derived_by"
);
compiler_case!(
    declaration_array_with_object,
    "runes/derived/declaration/array_with_object"
);
compiler_case!(
    declaration_boxed_nested_array,
    "runes/derived/declaration/boxed_nested_array"
);
compiler_case!(
    declaration_default_nested_array,
    "runes/derived/declaration/default_nested_array"
);
compiler_case!(
    declaration_derived_by_nested,
    "runes/derived/declaration/derived_by_nested"
);
compiler_case!(
    declaration_flat_object,
    "runes/derived/declaration/flat_object"
);
compiler_case!(
    declaration_nested_array,
    "runes/derived/declaration/nested_array"
);
compiler_case!(
    declaration_nested_object,
    "runes/derived/declaration/nested_object"
);
compiler_case!(
    declaration_object_of_arrays,
    "runes/derived/declaration/object_of_arrays"
);
compiler_case!(
    declaration_rest_nested_array,
    "runes/derived/declaration/rest_nested_array"
);
compiler_case!(
    declaration_single_array,
    "runes/derived/declaration/single_array"
);
compiler_case!(
    declaration_string_key,
    "runes/derived/declaration/string_key"
);

compiler_case!(
    write_update_postfix_inc,
    "runes/derived/write/update_postfix_inc"
);
compiler_case!(
    write_update_postfix_dec,
    "runes/derived/write/update_postfix_dec"
);
compiler_case!(
    write_update_prefix_inc,
    "runes/derived/write/update_prefix_inc"
);
compiler_case!(
    write_update_prefix_dec,
    "runes/derived/write/update_prefix_dec"
);
compiler_case!(write_compound_assign, "runes/derived/write/compound_assign");
compiler_case!(write_bind_value, "runes/derived/write/bind_value");
compiler_case!(
    write_plain_assign_guard,
    "runes/derived/write/plain_assign_guard"
);
compiler_case!(
    write_state_update_guard,
    "runes/derived/write/state_update_guard"
);
compiler_case!(
    write_derived_read_guard,
    "runes/derived/write/derived_read_guard"
);
