use super::*;

compiler_case!(assignment_array_default, "runes/state/assignment/array_default");
compiler_case!(assignment_array_pattern_reactive, "runes/state/assignment/array_pattern_reactive");
compiler_case!(assignment_array_rest, "runes/state/assignment/array_rest");
compiler_case!(assignment_async_default, "runes/state/assignment/async_default");
compiler_case!(assignment_async_value, "runes/state/assignment/async_value");
compiler_case!(assignment_computed_key, "runes/state/assignment/computed_key");
compiler_case!(assignment_default_nested_pattern, "runes/state/assignment/default_nested_pattern");
compiler_case!(assignment_expression_position, "runes/state/assignment/expression_position");
compiler_case!(assignment_guard_nonreactive_locals, "runes/state/assignment/guard_nonreactive_locals");
compiler_case!(assignment_guard_single_identifier, "runes/state/assignment/guard_single_identifier");
compiler_case!(assignment_member_target_mixed, "runes/state/assignment/member_target_mixed");
compiler_case!(assignment_nested_object_in_array, "runes/state/assignment/nested_object_in_array");
compiler_case!(assignment_nested_pattern, "runes/state/assignment/nested_pattern");
compiler_case!(assignment_nested_rest_pattern, "runes/state/assignment/nested_rest_pattern");
compiler_case!(assignment_object_pattern_ident_rhs, "runes/state/assignment/object_pattern_ident_rhs");
compiler_case!(assignment_object_pattern_literal_rhs, "runes/state/assignment/object_pattern_literal_rhs");
compiler_case!(assignment_object_rest, "runes/state/assignment/object_rest");
compiler_case!(declaration_alias, "runes/state/declaration/alias");
compiler_case!(declaration_array_hole, "runes/state/declaration/array_hole");
compiler_case!(declaration_array_of_objects, "runes/state/declaration/array_of_objects");
compiler_case!(declaration_array_rest, "runes/state/declaration/array_rest");
compiler_case!(declaration_array_rest_nested, "runes/state/declaration/array_rest_nested", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_computed_key, "runes/state/declaration/computed_key", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_default_intermediate_array, "runes/state/declaration/default_intermediate_array", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_default_intermediate_object, "runes/state/declaration/default_intermediate_object", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_default_leaf_array, "runes/state/declaration/default_leaf_array");
compiler_case!(declaration_default_leaf_object, "runes/state/declaration/default_leaf_object");
compiler_case!(declaration_flat_object, "runes/state/declaration/flat_object");
compiler_case!(declaration_nested_array, "runes/state/declaration/nested_array", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_nested_object, "runes/state/declaration/nested_object");
compiler_case!(declaration_object_in_array_in_object, "runes/state/declaration/object_in_array_in_object");
compiler_case!(declaration_object_of_arrays, "runes/state/declaration/object_of_arrays", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
compiler_case!(declaration_object_rest, "runes/state/declaration/object_rest");
compiler_case!(declaration_single_array, "runes/state/declaration/single_array");
compiler_case!(declaration_string_key, "runes/state/declaration/string_key", ignore = "binding-pattern-routing slice 4 ($state/$derived declaration, transform) · tag binding-pattern-routing#4");
