use super::*;

compiler_case!(
    declaration_legacy_alias,
    "snippets/declaration/legacy/alias"
);
compiler_case!(
    declaration_legacy_array_hole,
    "snippets/declaration/legacy/array_hole"
);
compiler_case!(
    declaration_legacy_array_of_objects,
    "snippets/declaration/legacy/array_of_objects"
);
compiler_case!(
    declaration_legacy_array_rest,
    "snippets/declaration/legacy/array_rest"
);
compiler_case!(
    declaration_legacy_array_rest_nested,
    "snippets/declaration/legacy/array_rest_nested"
);
compiler_case!(
    declaration_legacy_computed_key,
    "snippets/declaration/legacy/computed_key"
);
compiler_case!(
    declaration_legacy_default_intermediate_array,
    "snippets/declaration/legacy/default_intermediate_array"
);
compiler_case!(
    declaration_legacy_default_intermediate_object,
    "snippets/declaration/legacy/default_intermediate_object"
);
compiler_case!(
    declaration_legacy_default_leaf_array,
    "snippets/declaration/legacy/default_leaf_array"
);
compiler_case!(
    declaration_legacy_default_leaf_object,
    "snippets/declaration/legacy/default_leaf_object"
);
compiler_case!(
    declaration_legacy_flat_object,
    "snippets/declaration/legacy/flat_object"
);
compiler_case!(
    declaration_legacy_nested_array,
    "snippets/declaration/legacy/nested_array"
);
compiler_case!(
    declaration_legacy_nested_object,
    "snippets/declaration/legacy/nested_object"
);
compiler_case!(
    declaration_legacy_object_in_array_in_object,
    "snippets/declaration/legacy/object_in_array_in_object"
);
compiler_case!(
    declaration_legacy_object_of_arrays,
    "snippets/declaration/legacy/object_of_arrays"
);
compiler_case!(
    declaration_legacy_object_rest,
    "snippets/declaration/legacy/object_rest"
);
compiler_case!(
    declaration_legacy_single_array,
    "snippets/declaration/legacy/single_array"
);
compiler_case!(
    declaration_legacy_string_key,
    "snippets/declaration/legacy/string_key"
);
compiler_case!(declaration_runes_alias, "snippets/declaration/runes/alias");
compiler_case!(
    declaration_runes_array_hole,
    "snippets/declaration/runes/array_hole"
);
compiler_case!(
    declaration_runes_array_of_objects,
    "snippets/declaration/runes/array_of_objects"
);
compiler_case!(
    declaration_runes_array_rest,
    "snippets/declaration/runes/array_rest"
);
compiler_case!(
    declaration_runes_array_rest_nested,
    "snippets/declaration/runes/array_rest_nested"
);
compiler_case!(
    declaration_runes_computed_key,
    "snippets/declaration/runes/computed_key"
);
compiler_case!(
    declaration_runes_default_intermediate_array,
    "snippets/declaration/runes/default_intermediate_array"
);
compiler_case!(
    declaration_runes_default_intermediate_object,
    "snippets/declaration/runes/default_intermediate_object"
);
compiler_case!(
    declaration_runes_default_leaf_array,
    "snippets/declaration/runes/default_leaf_array"
);
compiler_case!(
    declaration_runes_default_leaf_object,
    "snippets/declaration/runes/default_leaf_object"
);
compiler_case!(
    declaration_runes_default_expression,
    "snippets/declaration/runes/default_expression"
);
compiler_case!(
    declaration_runes_flat_object,
    "snippets/declaration/runes/flat_object"
);
compiler_case!(
    declaration_runes_identifier_default,
    "snippets/declaration/runes/identifier_default"
);
compiler_case!(
    declaration_runes_mixed_default,
    "snippets/declaration/runes/mixed_default"
);
compiler_case!(
    declaration_runes_nested_array,
    "snippets/declaration/runes/nested_array"
);
compiler_case!(
    declaration_runes_nested_object,
    "snippets/declaration/runes/nested_object"
);
compiler_case!(
    declaration_runes_object_in_array_in_object,
    "snippets/declaration/runes/object_in_array_in_object"
);
compiler_case!(
    declaration_runes_object_of_arrays,
    "snippets/declaration/runes/object_of_arrays"
);
compiler_case!(
    declaration_runes_object_rest,
    "snippets/declaration/runes/object_rest"
);
compiler_case!(
    declaration_runes_single_array,
    "snippets/declaration/runes/single_array"
);
compiler_case!(
    declaration_runes_single_identifier,
    "snippets/declaration/runes/single_identifier"
);
compiler_case!(
    declaration_runes_string_key,
    "snippets/declaration/runes/string_key"
);
compiler_case!(
    deconflict_sibling_elements,
    "snippets/deconflict_sibling_elements",
    [prod, dev, ssr, ssr_dev]
);
