use super::*;

compiler_case!(assignment_alias, "stores/assignment/alias");
compiler_case!(assignment_array_hole, "stores/assignment/array_hole", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_array_of_objects, "stores/assignment/array_of_objects");
compiler_case!(assignment_array_rest, "stores/assignment/array_rest", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_array_rest_nested, "stores/assignment/array_rest_nested", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_computed_key, "stores/assignment/computed_key", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_default_intermediate_array, "stores/assignment/default_intermediate_array", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_default_intermediate_object, "stores/assignment/default_intermediate_object", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_default_leaf_array, "stores/assignment/default_leaf_array", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_default_leaf_object, "stores/assignment/default_leaf_object", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_flat_object, "stores/assignment/flat_object");
compiler_case!(assignment_nested_array, "stores/assignment/nested_array");
compiler_case!(assignment_nested_object, "stores/assignment/nested_object");
compiler_case!(assignment_object_in_array_in_object, "stores/assignment/object_in_array_in_object");
compiler_case!(assignment_object_of_arrays, "stores/assignment/object_of_arrays");
compiler_case!(assignment_object_rest, "stores/assignment/object_rest", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
compiler_case!(assignment_single_array, "stores/assignment/single_array");
compiler_case!(assignment_string_key, "stores/assignment/string_key", ignore = "destructure-patterns: assignment axis (walk_assignment_targets) — not binding-pattern-routing");
