[package]
name = "svelte_transform_server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
svelte_types = { workspace = true }
svelte_analyze = { workspace = true }
svelte_emit_builders = { workspace = true }
svelte_ast_builder = { workspace = true }
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_ast_visit = { workspace = true }
