import { compile, compileModule } from "svelte/compiler";
import { readFileSync } from "node:fs";

// Read from temp file written by the Rust caller, or fall back to /dev/stdin
const inputPath = process.env.INPUT_FILE || "/dev/stdin";
const files = JSON.parse(readFileSync(inputPath, "utf8"));
const results = {};
for (const file of files) {
  const text = readFileSync(file, "utf8");
  const isModule = file.endsWith('.svelte.js') || file.endsWith('.svelte.ts');
  const result = isModule
    ? compileModule(text, { dev: false })
    : compile(text, {
        discloseVersion: false,
        dev: false,
        name: "App",
        modernAst: true,
        runes: true,
      });
  let code = result.js.code;
  // Strip version comment from module output (we don't emit it)
  if (isModule) {
    code = code.replace(/^\/\*.*?generated by Svelte.*?\*\/\n/, "");
  }
  results[file] = code;
}
console.log(JSON.stringify(results));
