import { compile, compileModule } from "svelte/compiler";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";

// Read from temp file written by the Rust caller, or fall back to /dev/stdin
const inputPath = process.env.INPUT_FILE || "/dev/stdin";
const files = JSON.parse(readFileSync(inputPath, "utf8"));
const results = {};
for (const file of files) {
  const text = readFileSync(file, "utf8");
  const isModule = file.endsWith('.svelte.js') || file.endsWith('.svelte.ts');
  const isDiagnosticCase = file.includes('tasks/diagnostic_tests/cases/');

  // Per-case config override
  const caseDir = dirname(file);
  const configPath = join(caseDir, "config.json");
  let caseConfig = {};
  if (existsSync(configPath)) {
    caseConfig = JSON.parse(readFileSync(configPath, "utf8"));
  }

  if (isDiagnosticCase) {
    results[file] = {
      diagnostics: generateDiagnostics(text, caseConfig),
    };
    continue;
  }

  const result = isModule
    ? compileModule(text, { dev: false, ...caseConfig })
    : compile(text, {
        discloseVersion: false,
        dev: false,
        name: "App",
        modernAst: true,
        runes: true,
        ...caseConfig,
      });
  let code = result.js.code;
  // Strip version comment from module output (we don't emit it)
  if (isModule) {
    code = code.replace(/^\/\*.*?generated by Svelte.*?\*\/\n/, "");
  }
  results[file] = { js: code, css: result.css?.code ?? null };
}
console.log(JSON.stringify(results));

function generateDiagnostics(source, caseConfig) {
  try {
    const result = compile(source, {
      discloseVersion: false,
      dev: false,
      name: "App",
      modernAst: true,
      runes: true,
      ...caseConfig,
    });
    return result.warnings.map((warning) => normalizeDiagnostic(warning, "warning"));
  } catch (error) {
    return [normalizeDiagnostic(error, "error")];
  }
}

function normalizeDiagnostic(diagnostic, severity) {
  return {
    severity,
    code: diagnostic.code,
    start: diagnostic.position?.[0] ?? diagnostic.start?.character ?? 0,
    end: diagnostic.position?.[1] ?? diagnostic.end?.character ?? diagnostic.position?.[0] ?? 0,
  };
}
