name: CodSpeed (instrumentation)

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: bench-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_CHANNEL: '1.94.1'

jobs:
  instrumentation:
    name: Rust instruction-count
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ env.RUST_CHANNEL }}
          cache-target: release
          bins: cargo-codspeed
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build the benchmark target(s)
        run: cargo codspeed build --features codspeed -p benchmark

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
