name: CI

on:
  push:

env:
  RUST_CHANNEL: '1.94.1'

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain and cache
        uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ env.RUST_CHANNEL }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run tests
        run: cargo test --workspace
