name: CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain and cache
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable

      - name: Run tests
        run: cargo test --workspace
